<option value="طرابلس">طرابلس</option>
<option value="جنزور">جنزور</option>
<option value="الزاوية">الزاوية</option>
<option value="سوق الجمعة">سوق الجمعة</option>
<option value="تاجوراء">تاجوراء</option>
<option value="عين زارة">عين زارة</option>
<option value="غريان"> غريان</option>
<option value="غرب طرابلس">غرب طرابلس</option>
<option value="شرق طرابلس">شرق طرابلس</option>
<option value="جنوب طرابلس">جنوب طرابلس</option>
<option value="تاجوراء">تاجوراء</option>
<option value="القره بوللي">القره بوللي</option>
<option value="وادي الربيع">وادي الربيع</option>
<option value="مسلاته">مسلاته</option>
<option value="درنه">درنه</option>
<option value="ترهونة">ترهونة</option>
<option value="وازن">وازن</option>
<option value="مصراتة">مصراتة</option>
<option value="بنغازي">بنغازي</option>
<option value="سبها">سبها</option>